name: sfdx

on: 
    push:
        branches: [ master ]

    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: Write the secret JWT key into a file
          run: echo "$SUPER_SECRET" > secret.key
          env: 
            SUPER_SECRET: ${{ secrets.SERVER_KEY_CREDENTIALS_ID }}

        - name: Install Salesforce command line interface
#wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          run: |
            wget https://github.com/jasonodegaard/refactored-happiness/raw/master/binaries/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
          
        - name: Authenticate token with main org
          env: 
            SUPER_SECRET: ${{ secrets.SERVER_KEY_CREDENTIALS_ID }}
          run: sfdx auth:jwt:grant --clientid "3MVG9uudbyLbNPZOmSIknJGkXU3jB2EpUsRCx1AlAk6OkVgfSg8VG.asx_QWveV6iujTirl15DpvWT2gAOdvK" --jwtkeyfile "secret.key" --username "jason.odegaard@gmail.com" --instanceurl "https://login.salesforce.com"

        - name: Logout
          run: sfdx force:auth:logout -p -u jason.odegaard@gmail.com
####### The end?
